config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  	@firstname = "Chaiwa"
  	@lastname = "Berian"

  	@files = Dir.glob('*')

  	@counter = 0
  end

  def goodbye
  end
  def say_goodnight(name)
  	
  	result =  'Good Night ' + name
  	return result
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '**defaults**', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here.</p>
Say <%= link_to 'Hello', say_hello_path %>

app/views/say/hello.html.erb
<%= @firstname + " " + @lastname + " Says Hello!" %>
<p>
	It is now <%= @time %>
	Time in one hour will be:  <%= 1.hour.from_now.localtime%>
	<br/>
	<%= link_to "Goodbye",say_goodbye_path %> !
	<br/>
	Here is a list of files:

	<% for file in @files %>
		<% @counter = @counter + 1 %>
		<ol><%= @counter %> : <%= file %></ol>

	<%end %>

</p>